let loginData = {
    accountLevel: '',
    videoCoins: '',
    coins: '',
    taskRewards: [],
    llimit: [],
    flimit: [],
    rateString: '',
    inrVersion: '',
    defaultFreeCoin: '',
    ssEnabled: '',
    nativexEnabled: '',
    tapjoyEnabled: '',
    admobEnabled: '',
    inviteString: '',
    transfer: '',
    popMessage: '',
    faqUrl: '',
    getLoopsEnabled: '',
    getRevineEnabled: '',
    promoteAppDescription: '',
    iapGoods: [],
    getLikeGoods: [],
    getFollowGoods: [],
    getLoopsGoods: [],
    getStoreGoods: [],
    getCommentGoods: []
};
let config = {
    needtracklike: '',
    needtrackfollow: '',
    needrate: '',
    emurl: '',
    inr: '',
    unl: '',
    onlyo: '',
    buycomment: '',
    buyview: '',
    paypal: '',
    offline: '',
    kochavaenable: '',
    paypalonly: ''
};
let LoginUser = {
    username: '',
    password: '',
    avatarUrl: '',
    uuid: '',
    deviceId: '',
    userId: '',
    sessionToken: '',
    csrftoken: '',
    location: '',
    data: loginData,
    postsCount: '',
    followersCount: '',
    followingCount: ''
};
